# Generated by Django 5.0.2 on 2024-04-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0002_alter_interviewexperience_github'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewexperience',
            old_name='github',
            new_name='linkedin',
        ),
    ]
