# Generated by Django 5.0.2 on 2024-03-03 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementOfficer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgilePO',
            new_name='ProfilePO',
        ),
    ]
