# Generated by Django 5.0.2 on 2024-04-03 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementOfficer', '0002_rename_progilepo_profilepo'),
        ('Student', '0008_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnCampusJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('ctc', models.FloatField()),
                ('description', models.TextField(max_length=5500)),
            ],
        ),
        migrations.CreateModel(
            name='StudentOnCampusJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlacementOfficer.oncampusjobs')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.profile')),
            ],
        ),
    ]
