# Generated by Django 5.0.2 on 2024-02-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=1500, null=True)),
                ('company_name', models.CharField(blank=True, max_length=1500, null=True)),
                ('experience', models.CharField(blank=True, max_length=1500, null=True)),
                ('ctc', models.CharField(blank=True, max_length=1500, null=True)),
                ('link', models.CharField(blank=True, max_length=1500, null=True)),
                ('location', models.CharField(blank=True, max_length=1500, null=True)),
            ],
        ),
    ]
