# Generated by Django 5.0.2 on 2024-02-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_placementdetails_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdetails',
            name='ctc',
            field=models.IntegerField(default=0),
        ),
    ]
