# Generated by Django 5.0.2 on 2024-02-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_alter_placementdetails_ctc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdetails',
            name='ctc',
            field=models.FloatField(default=0),
        ),
    ]
